stages:
  get_data:
    cmd: python3 get_data.py
    deps:
    - get_data.py
    outs:
    - data/data_raw.csv  
  train:
    cmd: python3 train.py
    deps:
    - train.py
    - data/data_raw.csv
    outs:
    - models/finalized_model.pkl
    metrics:
    - metrics.json:
        cache: false